trunk/myapp/urls.py
# coding=utf-8
from django.conf.urls.defaults import *
from myapp import views

#urlpatterns = patterns('',
#    url(r'^index/$', views.index),
#    url(r'^add/$', views.add),
#)

trunk/myapp/models.py
# coding=utf-8
from django.db import models
from django.contrib import admin
from phonenumber_field.modelfields import PhoneNumberField
from myapp.translate.localize import *

class TripManager(models.Manager):
    def create_trip(self, date, type, place_from, place_to, name, phone_number, comments):
        trip = self.create(date=date, type=type, place_from=place_from, place_to=place_to, name=name, phone_number=phone_number, comments=comments)
        return trip

class Trip(models.Model):
	date = models.DateTimeField()
	type = models.CharField(max_length=150, choices=DEFAULT_TRIPTYPE)
	place_from = models.CharField(max_length=19, choices=DEFAULT_CITY)
	place_to = models.CharField(max_length=19, choices=DEFAULT_CITY)
	name = models.CharField(max_length=50)
	phone_number = PhoneNumberField()
	comments = models.TextField(max_length=200, null=True, blank=True)

	class Meta:
		ordering = ["date"]

	# def __str__(self):
	# 	return "place_from:{0} place_to:{1} date:{2} phone_number:{3} name:{4} type:{5} comments:{6}".format(self.place_from, 
	# 		self.place_to.encode('utf-8'), 
	# 		str(self.date), 
	# 		self.phone_number, 
	# 		self.name.encode('utf-8'), 
	# 		self.type.encode('utf-8'), 
	# 		self.comments.encode('utf-8'))
	def __unicode__(self):
		text = "phone_number:" + str(self.phone_number)
		return text
		# return "place_from:{0} place_to:{1} date:{2} phone_number:{3} name:{4} type:{5} comments:{6}".format(
		# 	self.place_from.encode('utf-8'), 
		# 	self.place_to.encode('utf-8'), 
		# 	str(self.date), 
		# 	self.phone_number, 
		# 	self.name.encode('utf-8'), 
		# 	self.type.encode('utf-8'), 
		# 	self.comments.encode('utf-8'))

	objects = TripManager()

class TripAdmin(admin.ModelAdmin):
	list_display = ('name', 'place_from', 'place_to', 'phone_number', 'date', 'type', )

admin.site.register(Trip, TripAdmin)

trunk/myapp/forms.py
# coding=utf-8
from django import forms
from django.core import validators
from django.forms import ModelForm, Textarea
from django.forms.util import ErrorList
from django.utils.timezone import utc
from django.utils import timezone
 
#python
import datetime
#my
from myapp.models import Trip
from myapp.translate.localize import *
#3rd party
from recaptchawidget.fields import ReCaptchaField 

"""
from django.forms.widgets import Widget
from __future__ import unicode_literals
Работает и без этого
def flatatt(attrs):
    return u''.join([u' %s="%s"' % (k, conditional_escape(v)) for k, v in attrs.items()])
	
class Label(Widget):    
    def render(self, name, value, attrs=None):
        if value is None: value = ''
        final_attrs = self.build_attrs(attrs, name=name)
       return mark_safe(u'<label%s>%s</label>' % (flatatt(final_attrs),
                conditional_escape(force_unicode(value))))
"""

jquery_input_class = 'ui-combobox-input ui-state-default ui-widget ui-widget-content ui-corner-left ui-corner-right'
jquery_combo_class = 'ui-combobox-input ui-state-default ui-widget ui-widget-content'

class DivModelForm(forms.ModelForm):
    error_css_class = 'class-error'
    #required_css_class = 'class-required'
    def as_div(self):
        return self._html_output(
            normal_row = u'<div%(html_class_attr)s>%(label)s %(field)s %(help_text)s %(errors)s</div>',
            #error_row = u'<div class="error">%s</div>',
			error_row = u'%s',
            row_ender = '</div>',
            help_text_html = u'<div class="hefp-text">%s</div>',
            errors_on_separate_row = False)

class TripForm(forms.ModelForm): #DivModelForm
	# captcha = ReCaptchaField()
	date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class':jquery_input_class}, format = DEFAULT_DATETIME_FORMAT_SERVER), input_formats=(DEFAULT_DATETIME_FORMAT_SERVER,))

	def __init__(self, *args, **kwargs):
		print '--------------------------------> call __init__ TripForm'

		self.request = kwargs.pop('request', None)
		super(TripForm, self).__init__(*args, **kwargs)
		self.label_suffix = ''
		d = DEFAULT_TRANSLATE_NEW_TRIP
				
		for name, field in self.fields.items():
			print name, field
			#localize label
			field.label = field.label if d.get(name) is None else d[name]
			#localize error msg
			for k,v in field.error_messages.items():
				field.error_messages[k] = DEFAULT_VALIDATION.get(k, v)
				
			if field.widget.__class__ == forms.widgets.Textarea:
				if field.widget.attrs.has_key('class'):
					field.widget.attrs['class'] += ' ' + jquery_input_class
				else:
					field.widget.attrs.update({'class':jquery_input_class})
			
			if field.widget.__class__ == forms.widgets.TextInput:
				if field.widget.attrs.has_key('class'):
					field.widget.attrs['class'] += ' ' + jquery_input_class
				else:
					field.widget.attrs.update({'class':jquery_input_class})

			if field.widget.__class__ == forms.widgets.Select:
				if field.widget.attrs.has_key('class'):
					field.widget.attrs['class'] += ' ' + jquery_combo_class
				else:
					field.widget.attrs.update({'class':jquery_combo_class})

	class Meta:
		model = Trip
		widgets = {
			'place_from': forms.Select(),
            'place_to': forms.Select(),
            'type': forms.Select(),
            'name': forms.TextInput(),
            'comments': Textarea(attrs={'cols': 40, 'rows': 5}),
			'phone_number':forms.TextInput(),
        }		
		
	def clean(self):
		print '--------------------------------> call clean'
		
		cleaned_data = super(TripForm, self).clean()
		date = cleaned_data.get("date")
		
		if date is None:
			self._errors["date"] = ErrorList([DEFAULT_VALIDATION['empty_date']]) 
			
		else:

			# now = datetime.datetime.utcnow().replace(tzinfo=utc) + datetime.timedelta(hours = 1)
			now = datetime.datetime.utcnow().replace(tzinfo=utc) # + datetime.timedelta(hours = 1)
			print 1111111111111
			print now
			now = timezone.make_naive(now, timezone.get_default_timezone())
			print 2222222222222
			print now
			print date
			# now = timezone.localtime(timezone.now()) - datetime.timedelta(hours = 1)
			if date < now:
				self._errors["date"] = ErrorList([DEFAULT_VALIDATION['less_current_date']]) 		

		place_from = cleaned_data.get("place_from")
		if place_from is None:
			self._errors["place_from"] = ErrorList([DEFAULT_VALIDATION['empty_place_from']])
	
		place_to = cleaned_data.get("place_to")
		if place_to is None:
			self._errors["place_to"] = ErrorList([DEFAULT_VALIDATION['empty_place_to']])
	
		type = cleaned_data.get("type")
		if type is None:
			self._errors["type"] = ErrorList([DEFAULT_VALIDATION['empty_type']])

		name = cleaned_data.get("name")
		if name is None:
			self._errors["name"] = ErrorList([DEFAULT_VALIDATION['empty_name']])
				
#TODO		
		phone_number = cleaned_data.get("phone_number")
		if phone_number != None and len(phone_number) < 11:
			self._errors["phone_number"] = ErrorList([DEFAULT_VALIDATION['invalid_phonenumber_length']])
		
		return cleaned_data

class TripFormCaptcha(TripForm): #DivModelForm
	captcha = ReCaptchaField()

trunk/myapp/templates/add.html
{% extends "base.html" %}

{% block source %}

	<link rel="stylesheet" type="text/css" media="screen" href="/content/css/jquery-ui-timepicker-addon.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="/content/css/jquery.combobox.css" />

	<script src="/content/js/jquery-ui-timepicker-addon.js"></script>
	<script src="/content/js/jquery.combobox.js" type="text/javascript"></script>
	
{% endblock %}		

{% load dict_by_key %}

{% block script %}

	<script type="text/javascript">

		$(function() {			
			all = ' Any'
			
			// LOCALIZE
			{% autoescape off %}			
			localize_datetime();
			{% endautoescape %}	
		
			// JQUERY INITIALIZE
			$("input[type=submit], button").button();
			$("#id_place_to").combobox();
			$("#id_place_from").combobox();
			$("#id_type").combobox();
			$('#id_date').datetimepicker();
			/*if ($('#id_date').val().length == 0) {
				$('#id_date').datetimepicker("setDate", new Date('{{date_from}}'));
			}
			*/
			$("#id_phone_number").val('{{ phonenumber }}');
			
			// Delete visi
			$("#id_type option[value='" + all + "']").remove();
			$("#id_place_to option[value='" + all + "']").remove();
			$("#id_place_from option[value='" + all + "']").remove();
			
			//Custom style
			// BEGIN FOR ILIJA
			$('form > table').children('tbody').children('tr').children('th').css('text-align', 'right');
            $('form > table').children('tbody').children('tr').children('th').css('color', 'EC8E0C')
           	//$('form > table').css('width', 432);
			// END FOR ILIJA
		
			//SET DEFAULTS/STYLE
			width = parseInt($('#id_type').next().children('input').css('width')) + parseInt($('#id_type').next().children('a').css('width'));
			width = width + ($.browser.msie ? 13 : -9);
			$('#id_name').width(width);
			$('#id_phone_number').width(width);	
			$('#id_date').width(width);	

			width = parseInt($('#recaptcha_image').parent().parent().width()) + ($.browser.msie ? 2 : 9);
			$('#id_comments').width(width);	
			$('[title^="Show All Items"]').attr('title', '{{ controls_translate|dict_getbykey:"ShowAllItems" }}');	
		});
		
	</script>	

{% endblock %}
		
{% block content %}

	<form action="/add/" method="post">
		{% csrf_token %}
		<table class="tableadd" color="white">
			{% autoescape off %}
			{% for field in form %}
				<tr>
					<th class="fieldWrapper">
						{{ field.label_tag }}
					</th>
					<td class="fieldWrapper">
						{{ field }}
					</td>
					<td class="fieldWrapper">
						{{ field.errors }}
					</td>
				</tr>
			{% endfor %}
			{% endautoescape %}
			<tr>
				<td></td>
				<td>
					<input src="../content/img/Icons/CC/Check.png" alt='{{ controls_translate|dict_getbykey:"Save_tooltip" }}' title='{{ controls_translate|dict_getbykey:"Save_tooltip" }}' type="image" value={{ controls_translate|dict_getbykey:"Save" }} name="save" style="width: 35px;" />
					<input src="../content/img/Icons/CC/Delete.png" alt='{{ controls_translate|dict_getbykey:"Trips_tooltip" }}' title='{{ controls_translate|dict_getbykey:"Trips_tooltip" }}' type="image" value={{ controls_translate|dict_getbykey:"Trips" }} id="trips" name="delete" style="width: 35px;" />
				</td>
			</tr>
		</table>
	</form>

{% endblock %}					

trunk/myapp/templates/base.html
<html>
<head>

	{% load dict_by_key %}

	<!-- <link rel="stylesheet" type="text/css" media="screen" href="/content/css/ui-darkness/jquery-ui-1.9.2.custom.css" /> -->
	<link rel="stylesheet" type="text/css" media="screen" href="/content/css/ui-darkness/jquery-ui-1.9.2.custom.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="/content/css/ui-darkness/my-jquery.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="/content/css/main.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="/content/css/select_height.css" />

    <link rel="shortcut icon" type="image/png" href="/content/img/favicon.png">
	
	<script src="/content/js/jquery-1.8.3.min.js"></script>
 	<script src="/content/js/jquery-ui-1.9.2.custom.min.js"></script>

	<script src="/content/js/json_parse.js"></script>
	<script src="/content/js/css_browser_selector.js"></script>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-language" content="lt" />
	<title>{{ controls_translate|dict_getbykey:"SiteName"}}</title>
	<meta name="description" content='{{ controls_translate|dict_getbykey:"SiteDescription"}}'/>
	<meta name="keywords" content="pakeleiviai, Lietuvos pakeleiviai, ieskau pakeleiviu, keliones, keliones po Lietuva, Lietuvos skelbimai, keliones Lietuvoje, pakeliui, keliauti, vaziuoja, vaziuoju, pigios keliones, keleivis, keleiviai, pilna masina, pilna, masina, keleiviu pervezimas, keleiviu vezimas, veza, vezimas, vezti, paves, atstumas tarp lietuvos miestu, kelias, keliai, marsrutas, marsrutai, pakeleiviu filtras, kartu, surask, kompanija, kompanijos, autostopu, autostopas, tranzavimas, tranzas, vaziavimas, pakeleiviu paieska, paieska, taksi, taxi, tarpmiestinis, tranzuoti, vairuotojai, keleiviai"/>

	<!-- Facebook Meta Tags -->
	<meta property="og:image" content="http://pilnamasina.lt/content/img/facebooklogo_2_changename.png"/>
	<meta property="og:image:type" content="image/png" />
	<meta property="og:image:width" content="124" />
	<meta property="og:image:height" content="124" />

	{% block source %}
	{% endblock %}		
	
	{% block includes %}
	{% endblock %}	
	
</head>
<body>
	<script type="text/javascript">
		// implement JSON.stringify serialization
		var JSON;
		if (!JSON) {
			JSON = {};
		}
	
		function json_stringify_IE(){		
			
			JSON.stringify = JSON.stringify || function (obj) {
				var t = typeof (obj);
				if (t != "object" || obj === null) {
					// simple data type
					if (t == "string") obj = '"'+obj+'"';
					return String(obj);
				}
				else {
					// recurse array or object
					var n, v, json = [], arr = (obj && obj.constructor == Array);
					for (n in obj) {
						v = obj[n]; t = typeof(v);
						if (t == "string") v = '"'+v+'"';
						else if (t == "object" && v !== null) v = JSON.stringify(v);
						json.push((arr ? "" : '"' + n + '":') + String(v));
					}
					return (arr ? "[" : "{") + String(json) + (arr ? "]" : "}");
				}
			};
		}
	
		// IE not support stringify
		jQuery.extend({
			stringify  : function stringify(obj) {
				var t = typeof (obj);
				if (t != "object" || obj === null) {
					// simple data type
					if (t == "string") obj = '"' + obj + '"';
					return String(obj);
				} else {
					// recurse array or object
					var n, v, json = [], arr = (obj && obj.constructor == Array);

					for (n in obj) {
						v = obj[n];
						t = typeof(v);
						
						if (obj.hasOwnProperty(n)) {
							if (t == "string") 
								v = '"' + v + '"'; 
							else if (t == "object" && v !== null) 
								v = jQuery.stringify(v);
								
							json.push((arr ? "" : '"' + n + '":') + String(v));
						}
					}
					return (arr ? "[" : "{") + String(json) + (arr ? "]" : "}");
				}
			}
		});
	
		// common functions
		function str_to_list(var_str){
			var res = new Array();
			arr = var_str.split(",");

			for (var i = 0; i < arr.length; i++) {
				res.push(arr[i]);
			}
			
			return res;
		}
		
		// IE don't has indexof method
		if(!Array.prototype.indexOf) {
			Array.prototype.indexOf = function(needle) {
				for(var i = 0; i < this.length; i++) {
					if(this[i] === needle) {
						return i;
					}
				}
				return -1;
			};
		}

		//TODO must be outside *.js file
		function localize_datetime(){
			$.timepicker.regional['ru'] = {
				timeOnlyTitle: '{{ time_translate|dict_getbykey:"timeOnlyTitle"}}',
				timeText: '{{ time_translate|dict_getbykey:"timeText"}}',
				hourText: '{{ time_translate|dict_getbykey:"hourText"}}',
				minuteText: '{{ time_translate|dict_getbykey:"minuteText"}}',
				secondText: '{{ time_translate|dict_getbykey:"secondText"}}',
				millisecText: '{{ time_translate|dict_getbykey:"millisecText"}}',
				timezoneText: '{{ time_translate|dict_getbykey:"timezoneText"}}',
				currentText: '{{ time_translate|dict_getbykey:"currentText"}}',
				closeText: '{{ time_translate|dict_getbykey:"closeText"}}',
				timeFormat: '{{ time_translate|dict_getbykey:"timeFormat"}}',
				amNames: str_to_list('{{ time_translate|dict_getbykey:"amNames"}}'),
				pmNames: str_to_list('{{ time_translate|dict_getbykey:"pmNames"}}'),
				isRTL: false
			};
			$.timepicker.setDefaults($.timepicker.regional['ru']);			
			$.datepicker.regional['ru'] = {
				closeText: '{{ date_translate|dict_getbykey:"closeText"}}',
				prevText: '{{ date_translate|dict_getbykey:"prevText"}}',
				nextText: '{{ date_translate|dict_getbykey:"nextText"}}',
				currentText: '{{ date_translate|dict_getbykey:"currentText"}}',
				monthNames:str_to_list('{{ date_translate|dict_getbykey:"monthNames"}}'),
				monthNamesShort: str_to_list('{{ date_translate|dict_getbykey:"monthNamesShort"}}'),
				dayNames: str_to_list('{{ date_translate|dict_getbykey:"dayNames"}}'),
				dayNamesShort: str_to_list('{{ date_translate|dict_getbykey:"dayNamesShort"}}'),
				dayNamesMin: str_to_list('{{ date_translate|dict_getbykey:"dayNamesMin"}}'),
				weekHeader: '{{ date_translate|dict_getbykey:"weekHeader"}}',
				dateFormat: '{{ date_translate|dict_getbykey:"dateFormat"}}',
				firstDay: 1,
				isRTL: false,
				showMonthAfterYear: false,
				yearSuffix: ''
			};
			$.datepicker.setDefaults($.datepicker.regional['ru']);		
		}
		

		// GOOGLE
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-39178692-1']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

	</script>	
	
	{% block script %}
	{% endblock %}		
	<table cellpadding="" cellspacing="" align="right" border="0">  
        <tr>
            <td>		
				<!-- Facebook -->
	            <a href="https://www.facebook.com/pages/Pilnamasinalt/661135753910646?ref=hl" target="_blank"><img class="header" src="/content/img/fb_logo.png"/ border="0"></a>
	        </td>
        <tr>			
	</table>
	<div id="wrap">	
		<div>
			<table width="925" border="0" align="center" cellpadding="25" cellspacing="0">
				<tr>
					<td>
						<a href="http://www.pilnamasina.lt" ><img class="header" align="left" src="/content/img/Pm_logo.png"/ border="0"></a>
					</td>
					<td>
						<a href="https://www.facebook.com/pages/Pilnamasinalt/661135753910646?ref=hl" target="_blank"><img src="/content/img/facebook_opros.png" border="0"></a><a href="mailto:labas@pilnamasina.lt?Subject=PM vartotojas(-a)"><img src="/content/img/mail_opros.png" border="0"></a>
					</td>
				</tr> 
			</table>
		</div>
		<div class="body" >
			<table align="center" id='maintable' cellspacing="5" border="0" cellpadding="0"  >
				<tbody>
					<tr>
						<td id='content' class="content" border="1" colspan="5" >
							{% block content %}
							{% endblock %}					
						</td>
					</tr>
					<tr>
					    <td width="93">
				        </td>
					    <td>
                             <iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FPilnamasinalt%2F661135753910646%3Fref%3Dhl&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;share=false&amp;height=21&amp;appId=512555318803574" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe>
						</td>
					</tr>
				</tbody>
			</table>	
		</div>
	</div>
	
	



	<!-- footer -->
	
	<div class="footer" style="width:102%; text-align:right;" border="0">
		{% block footer %}
                <table align="center" width="772" cellspacing="5" border="0" cellpadding="0" valign="top">
				<tr>
				<td colspan="2">
				<font color="white"><b>-------------------------------------------------------------------------------------------------------------------------------</b></font>
				</td>
			
				
				<tr>
				<td valign="top" width="80">
				<font color="white"><b>Draugai:</b></font>
				</td>
				<td valign="top">
				<a href="http://slapcia.lt" border="0" target="_blank"><img src="../content/img/friends/slapcia.lt_190x100.png" border="0"></a>
				&nbsp;&nbsp;&nbsp;
				<a href="http://ponasbicepsas.lt" border="0" target="_blank"><img src="../content/img/friends/ponasbicepsas_120x100.png" border="0"></a>
				</td>
				</tr>
				
				
				<tr>
				<td>
				</td>
				<td style="text-align:right;">
				<a href="mailto:labas@pilnamasina.lt?Subject=PM vartotojas(-a)">
				<img src="../content/img/email_pm.png" border="0">
			    </a>
				
				</tr>
				</table>

		{% endblock %}
	</div>
</body>
</html>

trunk/myapp/templates/google4d6b20cf8373e41a.html
google-site-verification: google4d6b20cf8373e41a.html

trunk/myapp/templates/test_template.html
<!doctype html>

<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>jQuery UI Autocomplete - Combobox</title>
	<!-- they
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />-->
	
	<!--
	<link rel="stylesheet" href="/resources/demos/style.css" />-->
	
	<!-- my-->
	<script src="/content/js/jquery-1.8.3.js"></script>
	<script src="/content/js/jquery-ui.js"></script>
	<link rel="stylesheet" type="text/css" media="screen" href="/content/css/ui-darkness/jquery-ui-1.9.2.custom.css" />
	 
	<!--<script src="/content/js/jquery-ui-1.9.2.custom.js" type="text/javascript"></script>
	<script src="/content/js/jquery-ui-1.9.2.custom.min.js" type="text/javascript"></script>
	<script src="/content/js/customjs/main.js" type="text/javascript"></script>
	-->
	
	<style>
	.ui-combobox {
		position: relative;
		display: inline-block;
	}
	.ui-combobox-toggle {
		position: absolute;
		top: 0;
		bottom: 0;
		margin-left: -1px;
		padding: 0;
		/* adjust styles for IE 6/7 */
		*height: 1.7em;
		*top: 0.1em;
	}
	.ui-combobox-input {
		margin: 0;
		padding: 0.3em;
	}
	</style>
	<script>
	(function( $ ) {
		$.widget( "ui.combobox", {
			_create: function() {
				var input,
					that = this,
					select = this.element.hide(),
					selected = select.children( ":selected" ),
					value = selected.val() ? selected.text() : "",
					wrapper = this.wrapper = $( "<span>" )
						.addClass( "ui-combobox" )
						.insertAfter( select );

				function removeIfInvalid(element) {
					var value = $( element ).val(),
						matcher = new RegExp( "^" + $.ui.autocomplete.escapeRegex( value ) + "$", "i" ),
						valid = false;
					select.children( "option" ).each(function() {
						if ( $( this ).text().match( matcher ) ) {
							this.selected = valid = true;
							return false;
						}
					});
					if ( !valid ) {
						// remove invalid value, as it didn't match anything
						$( element )
							.val( "" )
							.attr( "title", value + " didn't match any item" )
							.tooltip( "open" );
						select.val( "" );
						setTimeout(function() {
							input.tooltip( "close" ).attr( "title", "" );
						}, 2500 );
						input.data( "autocomplete" ).term = "";
						return false;
					}
				}

				input = $( "<input>" )
					.appendTo( wrapper )
					.val( value )
					.attr( "title", "" )
					.addClass( "ui-state-default ui-combobox-input" )
					.autocomplete({
						delay: 0,
						minLength: 0,
						source: function( request, response ) {
							var matcher = new RegExp( $.ui.autocomplete.escapeRegex(request.term), "i" );
							response( select.children( "option" ).map(function() {
								var text = $( this ).text();
								if ( this.value && ( !request.term || matcher.test(text) ) )
									return {
										label: text.replace(
											new RegExp(
												"(?![^&;]+;)(?!<[^<>]*)(" +
												$.ui.autocomplete.escapeRegex(request.term) +
												")(?![^<>]*>)(?![^&;]+;)", "gi"
											), "<strong>$1</strong>" ),
										value: text,
										option: this
									};
							}) );
						},
						select: function( event, ui ) {
							ui.item.option.selected = true;
							that._trigger( "selected", event, {
								item: ui.item.option
							});
						},
						change: function( event, ui ) {
							if ( !ui.item )
								return removeIfInvalid( this );
						}
					})
					.addClass( "ui-widget ui-widget-content ui-corner-left" );

				input.data( "autocomplete" )._renderItem = function( ul, item ) {
					return $( "<li>" )
						.data( "item.autocomplete", item )
						.append( "<a>" + item.label + "</a>" )
						.appendTo( ul );
				};

				$( "<a>" )
					.attr( "tabIndex", -1 )
					.attr( "title", "Show All Items" )
					.tooltip()
					.appendTo( wrapper )
					.button({
						icons: {
							primary: "ui-icon-triangle-1-s"
						},
						text: false
					})
					.removeClass( "ui-corner-all" )
					.addClass( "ui-corner-right ui-combobox-toggle" )
					.click(function() {
						// close if already visible
						if ( input.autocomplete( "widget" ).is( ":visible" ) ) {
							input.autocomplete( "close" );
							removeIfInvalid( input );
							return;
						}

						// work around a bug (likely same cause as #5265)
						$( this ).blur();

						// pass empty string as value to search for, displaying all results
						input.autocomplete( "search", "" );
						input.focus();
					});

					input
						.tooltip({
							position: {
								of: this.button
							},
							tooltipClass: "ui-state-highlight"
						});
			},

			destroy: function() {
				this.wrapper.remove();
				this.element.show();
				$.Widget.prototype.destroy.call( this );
			}
		});
	})( jQuery );

	$(function() {
		$( "#combobox" ).combobox();
		$( "#toggle" ).click(function() {
			$( "#combobox" ).toggle();
		});
	});
	</script>
</head>
<body>

<div class="ui-widget">
	<label>Your preferred programming language: </label>
	<select id="combobox">
		<option value="">Select one...</option>
		<option value="ActionScript">ActionScript</option>
		<option value="AppleScript">AppleScript</option>
		<option value="Asp">Asp</option>
		<option value="BASIC">BASIC</option>
		<option value="C">C</option>
		<option value="C++">C++</option>
		<option value="Clojure">Clojure</option>
		<option value="COBOL">COBOL</option>
		<option value="ColdFusion">ColdFusion</option>
		<option value="Erlang">Erlang</option>
		<option value="Fortran">Fortran</option>
		<option value="Groovy">Groovy</option>
		<option value="Haskell">Haskell</option>
		<option value="Java">Java</option>
		<option value="JavaScript">JavaScript</option>
		<option value="Lisp">Lisp</option>
		<option value="Perl">Perl</option>
		<option value="PHP">PHP</option>
		<option value="Python">Python</option>
		<option value="Ruby">Ruby</option>
		<option value="Scala">Scala</option>
		<option value="Scheme">Scheme</option>
	</select>
</div>
<button id="toggle">Show underlying select</button>


</body>
</html>